name: kinomir

volumes:
  postgres_data:
  static_files:
  media_files:

services:
  database:
    container_name: KinoMir-postgres
    env_file:
      - .env
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: KinoMir-redis
    image: redis
    restart: always

  backend:
    container_name: KinoMir-backend
    env_file:
      - .env
    build: .
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - ./:/app
    restart: always
    expose:
      - 8000
    depends_on:
      - database
      - redis
      - celery
    command: sh -c "make migrate &&
                    make loaddata &&
                    make collectstatic &&
                    make run-prod"

  celery:
    container_name: KinoMir-celery
    build:
      context: .
    restart: always
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: poetry run celery -A KinoMir worker -l info

  nginx:
    container_name: KinoMir-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - ./nginx/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    container_name: KinoMir-certbot
    image: certbot/certbot
    volumes:
      - ./nginx/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
