# Generated by Django 5.1.4 on 2024-12-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(help_text='Рекомендуемый размер 300x450', upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('age_limit', models.PositiveIntegerField(verbose_name='Возрастное ограничение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('genres', models.ManyToManyField(to='core.genre', verbose_name='Жанр')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'movies',
                'db_table_comment': 'Таблица содержит список фильмов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FilmParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Актёр'), ('director', 'Режиссёр'), ('producer', 'Продюсер'), ('screenwriter', 'Сценарист'), ('operator', 'Оператор')], max_length=50, verbose_name='Роль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Человек')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Член фильма',
                'verbose_name_plural': 'Члены фильма',
                'db_table': 'film_participants',
                'db_table_comment': 'Таблица содержит список членов фильма',
                'ordering': ('id',),
                'unique_together': {('movie', 'person')},
            },
        ),
    ]
